# Single server setup for dev

services:
  app:
    environment:
     - DATABASE_PORT=5432
     - DATABASE_DRIVER=pdo_pgsql
     - DATABASE_PLATFORM=pgsql
     - DATABASE_CHARSET=utf8
     - DATABASE_VERSION=18.0

  db:
    image: postgres:18.0
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    networks:
      - backend
    ports:
      - "5433:5432"
